import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import type {
    TemplateField,
    ThemeDefinition,
    ThemeFooter,
    ThemeSetting,
    ThemeTemplate,
} from './types.js';
import { isFileSystemError } from './utilities.js';

const GENERATED_TYPES_PATH = 'resources/js/.bopli/types.d.ts';

/** Generates the theme-specific TypeScript contract derived from inspected source metadata. */
export async function generateThemeTypes(theme: ThemeDefinition): Promise<string> {
    const output = join(theme.root, GENERATED_TYPES_PATH);
    const contents = typeDeclarations(theme);

    await mkdir(dirname(output), { recursive: true });
    if ((await existingContents(output)) !== contents) {
        await writeFile(output, contents);
    }

    return output;
}

/** Renders deterministic declaration source for one inspected theme. */
export function typeDeclarations(theme: ThemeDefinition): string {
    const declarations = [
        '// This file is generated by `bopli-theme types`. Do not edit it by hand.',
        '',
        'import type {',
        '    BopliBlogIndexProps,',
        '    BopliBlogPostProps,',
        '    BopliEntryProps,',
        '    BopliImage,',
        '    BopliThemeFooter,',
        '    BopliPageProps,',
        '    BopliPublicEntry,',
        '    BopliRelatedEntry,',
        "} from '@bopli/theme-sdk';",
        '',
        settingsDeclaration(theme.settings),
        '',
        ...footerDeclarations(theme.footer),
    ];

    for (const [handle, template] of Object.entries(theme.templates)) {
        declarations.push('', ...templateDeclarations(handle, template));
    }

    return `${declarations.join('\n')}\n`;
}

/** Returns generated aliases for a single Page, Entry, or native Blog template. */
function templateDeclarations(handle: string, template: ThemeTemplate): string[] {
    const name = typeName(handle);

    if (template.kind === 'page') {
        return [
            `export type ${name}Fields = {`,
            ...fieldProperties(template.fields ?? {}),
            '};',
            '',
            `export type ${name}Props = BopliPageProps<${name}Fields, ThemeSettings, ThemeFooter>;`,
        ];
    }

    if (template.kind === 'blog_index') {
        return [`export type ${name}Props = BopliBlogIndexProps<ThemeSettings, ThemeFooter>;`];
    }

    if (template.kind === 'blog_post') {
        return [`export type ${name}Props = BopliBlogPostProps<ThemeSettings, ThemeFooter>;`];
    }

    return [
        `export type ${name}Fields = {`,
        ...fieldProperties(template.fields ?? {}),
        '};',
        '',
        `export type ${name}Entry = BopliPublicEntry<${name}Fields> & {`,
        '    canonicalPath: string;',
        '    seoTitle: string | null;',
        '    seoDescription: string | null;',
        '};',
        '',
        `export type ${name}Props = BopliEntryProps<${name}Entry, ThemeSettings, ThemeFooter>;`,
    ];
}

function footerDeclarations(footer: ThemeFooter | null): string[] {
    const settings = footer?.settings ?? {};
    const fields = footer?.fields ?? {};

    return [
        settingsTypeDeclaration('FooterSettings', settings),
        '',
        'export type FooterContent = {',
        ...footerFieldProperties(fields),
        '};',
        '',
        'export type ThemeFooter = BopliThemeFooter<FooterSettings, FooterContent>;',
    ];
}

function footerFieldProperties(fields: Record<string, TemplateField>): string[] {
    return Object.entries(fields).map(
        ([handle, definition]) => `    ${propertyName(handle)}: ${fieldType(definition)};`,
    );
}

/** Produces the concrete settings object consumed by every generated props alias. */
function settingsDeclaration(settings: Record<string, ThemeSetting>): string {
    return settingsTypeDeclaration('ThemeSettings', settings);
}

function settingsTypeDeclaration(
    name: string,
    settings: Record<string, ThemeSetting>,
): string {
    const properties = Object.entries(settings).map(
        ([handle, setting]) => `    ${propertyName(handle)}: ${settingType(setting)};`,
    );

    if (properties.length === 0) return `export type ${name} = Record<never, never>;`;

    return [`export type ${name} = {`, ...properties, '};'].join('\n');
}

/** Maps a manifest setting declaration to its public runtime value. */
function settingType(setting: ThemeSetting): string {
    if (setting.type === 'boolean') return 'boolean';
    if (setting.type === 'image') return 'BopliImage | null';
    if (setting.type === 'select') {
        return (setting.options ?? []).map((option) => JSON.stringify(option)).join(' | ');
    }

    return 'string';
}

/** Maps a template field declaration to its projected public TypeScript value. */
function fieldType(field: TemplateField): string {
    if (field.type === 'list') {
        const children = Object.entries(field.fields ?? {})
            .map(
                ([handle, child]) =>
                    `${propertyName(handle)}${child.required === true ? '' : '?'}: ${fieldType(child)}${child.required === true ? '' : ' | null'}`,
            )
            .join('; ');

        return `Array<{ ${children}${children === '' ? '' : ';'} }>`;
    }
    if (field.type === 'number') return 'number';
    if (field.type === 'boolean') return 'boolean';
    if (field.type === 'image') return 'BopliImage | null';
    if (field.type === 'json') return 'unknown';
    if (field.type === 'relationship') return 'BopliRelatedEntry[]';

    return 'string';
}

/** Produces typed object properties for Page and Entry field contracts. */
function fieldProperties(fields: Record<string, TemplateField>): string[] {
    return Object.entries(fields).map(
        ([handle, definition]) =>
            `    ${propertyName(handle)}${definition.required === true ? '' : '?'}: ${fieldType(definition)}${definition.required === true || definition.type === 'image' ? '' : ' | null'};`,
    );
}

/** Converts a stable theme handle into a legal PascalCase type prefix. */
function typeName(handle: string): string {
    const name = handle
        .split(/[^A-Za-z0-9]+/)
        .filter(Boolean)
        .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
        .join('');

    return /^[A-Za-z_$]/.test(name) ? name : `Theme${name}`;
}

/** Uses an unquoted identifier when possible and a JSON string literal otherwise. */
function propertyName(handle: string): string {
    return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(handle) ? handle : JSON.stringify(handle);
}

/** Reads the previous declaration so unchanged generation does not disturb watch mode. */
async function existingContents(path: string): Promise<string | null> {
    try {
        return await readFile(path, 'utf8');
    } catch (error) {
        if (isFileSystemError(error, 'ENOENT')) return null;
        throw error;
    }
}
